name: MuleSoft CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Mule App
        run: mvn clean package -B

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}   # dev, qa, or prod
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Deploy to CloudHub
        env:
          ANYPOINT_USERNAME: Narsinga
          ANYPOINT_PASSWORD: Narsing@006
        run: |
          mvn deploy \
            -DmuleDeploy \
            -Danypoint.username=Narsinga \
            -Danypoint.password=Narsing@006 \
            -DskipTests \
            -Danypoint.environment=${{ github.ref_name }}
