#%RAML 1.0 NamedExample
  {
    "firstName": "John",
    "LastName": "Doe",
    "age": 45,
    "gender": "Male",
    "phoneNumber": "+916858975865",
    "address": "123, NTR Hospital, Anakapalle",
    "gmail": "johndoe@gmail.com"
  }