#%RAML 1.0 NamedExample
{
  "hospitalId": "1",
  "services": [
    {
      "serviceId": "1",
      "name": "Cardiology",
      "description": "Heart and cardiovascular treatments"
    },
    {
      "serviceId": "2",
      "name": "Radiology",
      "description": "X-rays, MRI, CT scans"
    },
    {
      "serviceId": "3",
      "name": "Pharmacy",
      "description": "Medicines and prescriptions"
    }
  ]
}

