name: Cleanup and Deploy MuleSoft App

on:
  push:
    branches:
      - main    # Or the branch you deploy from
  workflow_dispatch:  # Allows manual trigger

jobs:
  cleanup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Delete specific files/folders
      - name: Cleanup unnecessary files
        run: |
          echo "Deleting temporary files and folders..."
          rm -rf target/
          rm -rf logs/
          rm -f *.tmp
          # Add any additional files/folders you want to remove
          git status

      # Step 3: Commit deletions (optional)
      - name: Commit deletions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Cleanup temp files before deployment"
      
      # Step 4: Deploy to Anypoint/CloudHub
      - name: Deploy Mule Application
        run: |
          echo "Deploying Mule app..."
          mvn clean package mule:deploy \
            -Dmule.username=${{ secrets.ANYPOINT_USERNAME }} \
            -Dmule.password=${{ secrets.ANYPOINT_PASSWORD }} \
            -Dmule.env=qa \
            -Dmule.appName=hospital-locator-api
