name: MuleSoft CI/CD Deployment

on:
  push:
    branches:
      - main   # Deploy only when pushing to main branch
  workflow_dispatch:   # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up JDK 8 (required for Mule 4.x builds)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      # 3. Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Build the Mule application
      - name: Build Mule App
        run: mvn clean package -DskipTests

      # 5. Run Unit Tests (MUnit)
      - name: Run MUnit Tests
        run: mvn test

      # 6. Deploy to CloudHub
      - name: Deploy to CloudHub
        run: |
          mvn mule:deploy \
            -DmuleDeploy \
            -DconnectedAppClientId=${{ secrets.ANYPOINT_CLIENT_ID }} \
            -DconnectedAppClientSecret=${{ secrets.ANYPOINT_CLIENT_SECRET }} \
            -Danypoint.environment=qa \
            -Dapp.name=hospital-locator-api
