name: Deploy Mule App to QA

on:
  workflow_run:
    workflows: ["Build and Test Mule App"]
    types:
      - completed

jobs:
  deploy-to-qa:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact
          path: target/

      - name: Deploy to CloudHub QA
        run: |
          mvn mule:deploy \
            -DmuleDeploy \
            -DconnectedAppClientId=${{ secrets.ANYPOINT_CLIENT_ID_QA }} \
            -DconnectedAppClientSecret=${{ secrets.ANYPOINT_CLIENT_SECRET_QA }} \
            -Danypoint.environment=qa \
            -Dapp.name=hospital-locator-api
