name: Deploy Mule App to PROD

on:
  workflow_dispatch:   # Manual trigger only

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Deploy to CloudHub PROD
      - name: Deploy to CloudHub PROD
        run: |
          mvn mule:deploy \
            -DmuleDeploy \
            -DconnectedAppClientId=${{ secrets.ANYPOINT_CLIENT_ID }} \
            -DconnectedAppClientSecret=${{ secrets.ANYPOINT_CLIENT_SECRET }} \
            -Danypoint.environment=prod \
            -Dapp.name=hospital-locator-api
