name: Deploy Mule App to PROD

on:
  workflow_run:
    workflows: ["Deploy Mule App to QA"]   # 👈 runs after QA workflow finishes
    types:
      - completed

jobs:
  deploy-to-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: prod  # 👈 requires approval in GitHub Environment
      url: https://anypoint.mulesoft.com

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Download the exact artifact from QA
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact
          path: target/

      - name: Deploy to CloudHub PROD
        run: |
          mvn mule:deploy \
            -DmuleDeploy \
            -DconnectedAppClientId=${{ secrets.ANYPOINT_CLIENT_ID_PROD }} \
            -DconnectedAppClientSecret=${{ secrets.ANYPOINT_CLIENT_SECRET_PROD }} \
            -Danypoint.environment=prod \
            -Dapp.name=hospital-locator-api
